### ISSUE TITLE
Combo box instead of simple seach field

### ISSUE THREAD

**Issue by brady77** [CulturePlex/Sylva#24]
Hi,

while editing data (*Graph name* -> Data -> *Data type name* - > Edit), the only option how to fill in the related node is by searching. It is sometimes easier to choose from a list than to recall the lellers from a word (or from a phrase). Is it possible to change the search-only field to a [combo-box](http://en.wikipedia.org/wiki/Combo_box) - a combination of a list with search field?

![2015-02-26_145326](https://cloud.githubusercontent.com/assets/8817469/6393126/d9caf5fe-bdc7-11e4-9360-65d064b6a1ca.png)

Thanks.

**Comment by versae** [comment]
If you are using your own instance of SylvaDB, yes, it is possible. Just set `ENABLE_AUTOCOMPLETE_NODES` to `False` in your (settings file)[https://github.com/CulturePlex/Sylva/blob/develop/sylva/sylva/settings.py#L315]

For the online version sylvadb.com, we cannot know in advance what the user preference would be. But we would think on adding that as a user preference rather than a system preference.

**Comment by brady77** [comment]
I just tested the SylvaDB setting and I got the drop-down list. Great. 

Nevertheless, what about the combobox? Having both the drop-down list and the seach field at the same time is even better. :) Would you consider to add it to your list of improvements? For sure not a must-have feature...

Thanks.

**Comment by versae** [comment]
Sure, although this has low priority ;)

**Comment by versae** [comment]
There is now (7602db1) a `ENABLE_AUTOCOMPLETE_NODES_COMBO` settings that can be set to `True` when `ENABLE_AUTOCOMPLETE_NODES` is `False`, and that will add the combo box behaviour.
